// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: notes/api.proto

package notes

import (
	__common "github.com/venomous-dashboard/api-gateway/internal/types/proto_generated/_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoListRequest) Reset() {
	*x = MemoListRequest{}
	mi := &file_notes_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoListRequest) ProtoMessage() {}

func (x *MemoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoListRequest.ProtoReflect.Descriptor instead.
func (*MemoListRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{0}
}

type MemoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          []*Memo                `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoListResponse) Reset() {
	*x = MemoListResponse{}
	mi := &file_notes_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoListResponse) ProtoMessage() {}

func (x *MemoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoListResponse.ProtoReflect.Descriptor instead.
func (*MemoListResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{1}
}

func (x *MemoListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoListResponse) GetData() []*Memo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoListResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MemoGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoGetRequest) Reset() {
	*x = MemoGetRequest{}
	mi := &file_notes_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoGetRequest) ProtoMessage() {}

func (x *MemoGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoGetRequest.ProtoReflect.Descriptor instead.
func (*MemoGetRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{2}
}

func (x *MemoGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MemoGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *Memo                  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoGetResponse) Reset() {
	*x = MemoGetResponse{}
	mi := &file_notes_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoGetResponse) ProtoMessage() {}

func (x *MemoGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoGetResponse.ProtoReflect.Descriptor instead.
func (*MemoGetResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{3}
}

func (x *MemoGetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoGetResponse) GetData() *Memo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoGetResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MemoCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Color         MemoColor              `protobuf:"varint,2,opt,name=color,proto3,enum=venomous_dashboard.notes.MemoColor" json:"color,omitempty"`
	IsPinned      bool                   `protobuf:"varint,3,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoCreateRequest) Reset() {
	*x = MemoCreateRequest{}
	mi := &file_notes_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoCreateRequest) ProtoMessage() {}

func (x *MemoCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoCreateRequest.ProtoReflect.Descriptor instead.
func (*MemoCreateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{4}
}

func (x *MemoCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoCreateRequest) GetColor() MemoColor {
	if x != nil {
		return x.Color
	}
	return MemoColor_YELLOW
}

func (x *MemoCreateRequest) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type MemoCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *Memo                  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoCreateResponse) Reset() {
	*x = MemoCreateResponse{}
	mi := &file_notes_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoCreateResponse) ProtoMessage() {}

func (x *MemoCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoCreateResponse.ProtoReflect.Descriptor instead.
func (*MemoCreateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{5}
}

func (x *MemoCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoCreateResponse) GetData() *Memo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoCreateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MemoUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Color         *MemoColor             `protobuf:"varint,3,opt,name=color,proto3,enum=venomous_dashboard.notes.MemoColor,oneof" json:"color,omitempty"`
	IsPinned      *bool                  `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3,oneof" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoUpdateRequest) Reset() {
	*x = MemoUpdateRequest{}
	mi := &file_notes_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoUpdateRequest) ProtoMessage() {}

func (x *MemoUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoUpdateRequest.ProtoReflect.Descriptor instead.
func (*MemoUpdateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{6}
}

func (x *MemoUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoUpdateRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *MemoUpdateRequest) GetColor() MemoColor {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return MemoColor_YELLOW
}

func (x *MemoUpdateRequest) GetIsPinned() bool {
	if x != nil && x.IsPinned != nil {
		return *x.IsPinned
	}
	return false
}

type MemoUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *Memo                  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoUpdateResponse) Reset() {
	*x = MemoUpdateResponse{}
	mi := &file_notes_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoUpdateResponse) ProtoMessage() {}

func (x *MemoUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoUpdateResponse.ProtoReflect.Descriptor instead.
func (*MemoUpdateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{7}
}

func (x *MemoUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoUpdateResponse) GetData() *Memo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoUpdateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MemoDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoDeleteRequest) Reset() {
	*x = MemoDeleteRequest{}
	mi := &file_notes_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoDeleteRequest) ProtoMessage() {}

func (x *MemoDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoDeleteRequest.ProtoReflect.Descriptor instead.
func (*MemoDeleteRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{8}
}

func (x *MemoDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MemoDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoDeleteResponse) Reset() {
	*x = MemoDeleteResponse{}
	mi := &file_notes_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoDeleteResponse) ProtoMessage() {}

func (x *MemoDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoDeleteResponse.ProtoReflect.Descriptor instead.
func (*MemoDeleteResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{9}
}

func (x *MemoDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoDeleteResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ArticleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListRequest) Reset() {
	*x = ArticleListRequest{}
	mi := &file_notes_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListRequest) ProtoMessage() {}

func (x *ArticleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListRequest.ProtoReflect.Descriptor instead.
func (*ArticleListRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{10}
}

type ArticleListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Success       bool                       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          []*ArticleWithChapterCount `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Error         *__common.ApiError         `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListResponse) Reset() {
	*x = ArticleListResponse{}
	mi := &file_notes_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListResponse) ProtoMessage() {}

func (x *ArticleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListResponse.ProtoReflect.Descriptor instead.
func (*ArticleListResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{11}
}

func (x *ArticleListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleListResponse) GetData() []*ArticleWithChapterCount {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArticleListResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ArticleWithChapterCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	ChapterCount  int32                  `protobuf:"varint,2,opt,name=chapter_count,json=chapterCount,proto3" json:"chapter_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleWithChapterCount) Reset() {
	*x = ArticleWithChapterCount{}
	mi := &file_notes_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleWithChapterCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleWithChapterCount) ProtoMessage() {}

func (x *ArticleWithChapterCount) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleWithChapterCount.ProtoReflect.Descriptor instead.
func (*ArticleWithChapterCount) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{12}
}

func (x *ArticleWithChapterCount) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ArticleWithChapterCount) GetChapterCount() int32 {
	if x != nil {
		return x.ChapterCount
	}
	return 0
}

type ArticleGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleGetRequest) Reset() {
	*x = ArticleGetRequest{}
	mi := &file_notes_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleGetRequest) ProtoMessage() {}

func (x *ArticleGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleGetRequest.ProtoReflect.Descriptor instead.
func (*ArticleGetRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{13}
}

func (x *ArticleGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArticleGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *ArticleWithChapters   `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleGetResponse) Reset() {
	*x = ArticleGetResponse{}
	mi := &file_notes_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleGetResponse) ProtoMessage() {}

func (x *ArticleGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleGetResponse.ProtoReflect.Descriptor instead.
func (*ArticleGetResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{14}
}

func (x *ArticleGetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleGetResponse) GetData() *ArticleWithChapters {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArticleGetResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ArticleWithChapters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Chapters      []*ArticleChapter      `protobuf:"bytes,2,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleWithChapters) Reset() {
	*x = ArticleWithChapters{}
	mi := &file_notes_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleWithChapters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleWithChapters) ProtoMessage() {}

func (x *ArticleWithChapters) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleWithChapters.ProtoReflect.Descriptor instead.
func (*ArticleWithChapters) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{15}
}

func (x *ArticleWithChapters) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ArticleWithChapters) GetChapters() []*ArticleChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type ArticleCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleCreateRequest) Reset() {
	*x = ArticleCreateRequest{}
	mi := &file_notes_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCreateRequest) ProtoMessage() {}

func (x *ArticleCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCreateRequest.ProtoReflect.Descriptor instead.
func (*ArticleCreateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{16}
}

func (x *ArticleCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleCreateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ArticleCreateRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ArticleCreateRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

type ArticleCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *Article               `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleCreateResponse) Reset() {
	*x = ArticleCreateResponse{}
	mi := &file_notes_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCreateResponse) ProtoMessage() {}

func (x *ArticleCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCreateResponse.ProtoReflect.Descriptor instead.
func (*ArticleCreateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{17}
}

func (x *ArticleCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleCreateResponse) GetData() *Article {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArticleCreateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ArticleUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Status        *ArticleStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=venomous_dashboard.notes.ArticleStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleUpdateRequest) Reset() {
	*x = ArticleUpdateRequest{}
	mi := &file_notes_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleUpdateRequest) ProtoMessage() {}

func (x *ArticleUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleUpdateRequest.ProtoReflect.Descriptor instead.
func (*ArticleUpdateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{18}
}

func (x *ArticleUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArticleUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ArticleUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ArticleUpdateRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ArticleUpdateRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *ArticleUpdateRequest) GetStatus() ArticleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ArticleStatus_DRAFT
}

type ArticleUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *Article               `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleUpdateResponse) Reset() {
	*x = ArticleUpdateResponse{}
	mi := &file_notes_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleUpdateResponse) ProtoMessage() {}

func (x *ArticleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleUpdateResponse.ProtoReflect.Descriptor instead.
func (*ArticleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{19}
}

func (x *ArticleUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleUpdateResponse) GetData() *Article {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArticleUpdateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ArticleDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDeleteRequest) Reset() {
	*x = ArticleDeleteRequest{}
	mi := &file_notes_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDeleteRequest) ProtoMessage() {}

func (x *ArticleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDeleteRequest.ProtoReflect.Descriptor instead.
func (*ArticleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{20}
}

func (x *ArticleDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArticleDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDeleteResponse) Reset() {
	*x = ArticleDeleteResponse{}
	mi := &file_notes_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDeleteResponse) ProtoMessage() {}

func (x *ArticleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDeleteResponse.ProtoReflect.Descriptor instead.
func (*ArticleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{21}
}

func (x *ArticleDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleDeleteResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ChapterGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterGetRequest) Reset() {
	*x = ChapterGetRequest{}
	mi := &file_notes_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterGetRequest) ProtoMessage() {}

func (x *ChapterGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterGetRequest.ProtoReflect.Descriptor instead.
func (*ChapterGetRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{22}
}

func (x *ChapterGetRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ChapterGetRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

type ChapterGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *ArticleChapter        `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterGetResponse) Reset() {
	*x = ChapterGetResponse{}
	mi := &file_notes_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterGetResponse) ProtoMessage() {}

func (x *ChapterGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterGetResponse.ProtoReflect.Descriptor instead.
func (*ChapterGetResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{23}
}

func (x *ChapterGetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChapterGetResponse) GetData() *ArticleChapter {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChapterGetResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ChapterCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ChapterNumber int32                  `protobuf:"varint,4,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	WordCount     int32                  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterCreateRequest) Reset() {
	*x = ChapterCreateRequest{}
	mi := &file_notes_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterCreateRequest) ProtoMessage() {}

func (x *ChapterCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterCreateRequest.ProtoReflect.Descriptor instead.
func (*ChapterCreateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{24}
}

func (x *ChapterCreateRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ChapterCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChapterCreateRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *ChapterCreateRequest) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

type ChapterCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *ArticleChapter        `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterCreateResponse) Reset() {
	*x = ChapterCreateResponse{}
	mi := &file_notes_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterCreateResponse) ProtoMessage() {}

func (x *ChapterCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterCreateResponse.ProtoReflect.Descriptor instead.
func (*ChapterCreateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{25}
}

func (x *ChapterCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChapterCreateResponse) GetData() *ArticleChapter {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChapterCreateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ChapterUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
	WordCount     *int32                 `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3,oneof" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterUpdateRequest) Reset() {
	*x = ChapterUpdateRequest{}
	mi := &file_notes_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterUpdateRequest) ProtoMessage() {}

func (x *ChapterUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterUpdateRequest.ProtoReflect.Descriptor instead.
func (*ChapterUpdateRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{26}
}

func (x *ChapterUpdateRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ChapterUpdateRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *ChapterUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ChapterUpdateRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ChapterUpdateRequest) GetWordCount() int32 {
	if x != nil && x.WordCount != nil {
		return *x.WordCount
	}
	return 0
}

type ChapterUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *ArticleChapter        `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterUpdateResponse) Reset() {
	*x = ChapterUpdateResponse{}
	mi := &file_notes_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterUpdateResponse) ProtoMessage() {}

func (x *ChapterUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterUpdateResponse.ProtoReflect.Descriptor instead.
func (*ChapterUpdateResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{27}
}

func (x *ChapterUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChapterUpdateResponse) GetData() *ArticleChapter {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChapterUpdateResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ChapterDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterDeleteRequest) Reset() {
	*x = ChapterDeleteRequest{}
	mi := &file_notes_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterDeleteRequest) ProtoMessage() {}

func (x *ChapterDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterDeleteRequest.ProtoReflect.Descriptor instead.
func (*ChapterDeleteRequest) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{28}
}

func (x *ChapterDeleteRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ChapterDeleteRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

type ChapterDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterDeleteResponse) Reset() {
	*x = ChapterDeleteResponse{}
	mi := &file_notes_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterDeleteResponse) ProtoMessage() {}

func (x *ChapterDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterDeleteResponse.ProtoReflect.Descriptor instead.
func (*ChapterDeleteResponse) Descriptor() ([]byte, []int) {
	return file_notes_api_proto_rawDescGZIP(), []int{29}
}

func (x *ChapterDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChapterDeleteResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_notes_api_proto protoreflect.FileDescriptor

const file_notes_api_proto_rawDesc = "" +
	"\n" +
	"\x0fnotes/api.proto\x12\x18venomous_dashboard.notes\x1a\x17_common/interface.proto\x1a\x15notes/interface.proto\"\x11\n" +
	"\x0fMemoListRequest\"\xaa\x01\n" +
	"\x10MemoListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x04data\x18\x02 \x03(\v2\x1e.venomous_dashboard.notes.MemoR\x04data\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\" \n" +
	"\x0eMemoGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x01\n" +
	"\x0fMemoGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.venomous_dashboard.notes.MemoH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\x85\x01\n" +
	"\x11MemoCreateRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x129\n" +
	"\x05color\x18\x02 \x01(\x0e2#.venomous_dashboard.notes.MemoColorR\x05color\x12\x1b\n" +
	"\tis_pinned\x18\x03 \x01(\bR\bisPinned\"\xba\x01\n" +
	"\x12MemoCreateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.venomous_dashboard.notes.MemoH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\xc8\x01\n" +
	"\x11MemoUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12>\n" +
	"\x05color\x18\x03 \x01(\x0e2#.venomous_dashboard.notes.MemoColorH\x01R\x05color\x88\x01\x01\x12 \n" +
	"\tis_pinned\x18\x04 \x01(\bH\x02R\bisPinned\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\b\n" +
	"\x06_colorB\f\n" +
	"\n" +
	"_is_pinned\"\xba\x01\n" +
	"\x12MemoUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.venomous_dashboard.notes.MemoH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"#\n" +
	"\x11MemoDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\x12MemoDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x05error\x18\x02 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x14\n" +
	"\x12ArticleListRequest\"\xc0\x01\n" +
	"\x13ArticleListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12E\n" +
	"\x04data\x18\x02 \x03(\v21.venomous_dashboard.notes.ArticleWithChapterCountR\x04data\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"{\n" +
	"\x17ArticleWithChapterCount\x12;\n" +
	"\aarticle\x18\x01 \x01(\v2!.venomous_dashboard.notes.ArticleR\aarticle\x12#\n" +
	"\rchapter_count\x18\x02 \x01(\x05R\fchapterCount\"#\n" +
	"\x11ArticleGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x12ArticleGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12F\n" +
	"\x04data\x18\x02 \x01(\v2-.venomous_dashboard.notes.ArticleWithChaptersH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\x98\x01\n" +
	"\x13ArticleWithChapters\x12;\n" +
	"\aarticle\x18\x01 \x01(\v2!.venomous_dashboard.notes.ArticleR\aarticle\x12D\n" +
	"\bchapters\x18\x02 \x03(\v2(.venomous_dashboard.notes.ArticleChapterR\bchapters\"\xd2\x01\n" +
	"\x14ArticleCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x01R\bcategory\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tH\x02R\rcoverImageUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\x12\n" +
	"\x10_cover_image_url\"\xc0\x01\n" +
	"\x15ArticleCreateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\x04data\x18\x02 \x01(\v2!.venomous_dashboard.notes.ArticleH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\xc2\x02\n" +
	"\x14ArticleUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x02R\bcategory\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x03R\rcoverImageUrl\x88\x01\x01\x12D\n" +
	"\x06status\x18\x06 \x01(\x0e2'.venomous_dashboard.notes.ArticleStatusH\x04R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\x12\n" +
	"\x10_cover_image_urlB\t\n" +
	"\a_status\"\xc0\x01\n" +
	"\x15ArticleUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\x04data\x18\x02 \x01(\v2!.venomous_dashboard.notes.ArticleH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"&\n" +
	"\x14ArticleDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x15ArticleDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x05error\x18\x02 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"Q\n" +
	"\x11ChapterGetRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\"\xc4\x01\n" +
	"\x12ChapterGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12A\n" +
	"\x04data\x18\x02 \x01(\v2(.venomous_dashboard.notes.ArticleChapterH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\xab\x01\n" +
	"\x14ChapterCreateRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12%\n" +
	"\x0echapter_number\x18\x04 \x01(\x05R\rchapterNumber\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\"\xc7\x01\n" +
	"\x15ChapterCreateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12A\n" +
	"\x04data\x18\x02 \x01(\v2(.venomous_dashboard.notes.ArticleChapterH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"\xd7\x01\n" +
	"\x14ChapterUpdateRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x04 \x01(\tH\x01R\acontent\x88\x01\x01\x12\"\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05H\x02R\twordCount\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\r\n" +
	"\v_word_count\"\xc7\x01\n" +
	"\x15ChapterUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12A\n" +
	"\x04data\x18\x02 \x01(\v2(.venomous_dashboard.notes.ArticleChapterH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"T\n" +
	"\x14ChapterDeleteRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\"{\n" +
	"\x15ChapterDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x05error\x18\x02 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorBPZNgithub.com/venomous-dashboard/api-gateway/internal/types/proto_generated/notesb\x06proto3"

var (
	file_notes_api_proto_rawDescOnce sync.Once
	file_notes_api_proto_rawDescData []byte
)

func file_notes_api_proto_rawDescGZIP() []byte {
	file_notes_api_proto_rawDescOnce.Do(func() {
		file_notes_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notes_api_proto_rawDesc), len(file_notes_api_proto_rawDesc)))
	})
	return file_notes_api_proto_rawDescData
}

var file_notes_api_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_notes_api_proto_goTypes = []any{
	(*MemoListRequest)(nil),         // 0: venomous_dashboard.notes.MemoListRequest
	(*MemoListResponse)(nil),        // 1: venomous_dashboard.notes.MemoListResponse
	(*MemoGetRequest)(nil),          // 2: venomous_dashboard.notes.MemoGetRequest
	(*MemoGetResponse)(nil),         // 3: venomous_dashboard.notes.MemoGetResponse
	(*MemoCreateRequest)(nil),       // 4: venomous_dashboard.notes.MemoCreateRequest
	(*MemoCreateResponse)(nil),      // 5: venomous_dashboard.notes.MemoCreateResponse
	(*MemoUpdateRequest)(nil),       // 6: venomous_dashboard.notes.MemoUpdateRequest
	(*MemoUpdateResponse)(nil),      // 7: venomous_dashboard.notes.MemoUpdateResponse
	(*MemoDeleteRequest)(nil),       // 8: venomous_dashboard.notes.MemoDeleteRequest
	(*MemoDeleteResponse)(nil),      // 9: venomous_dashboard.notes.MemoDeleteResponse
	(*ArticleListRequest)(nil),      // 10: venomous_dashboard.notes.ArticleListRequest
	(*ArticleListResponse)(nil),     // 11: venomous_dashboard.notes.ArticleListResponse
	(*ArticleWithChapterCount)(nil), // 12: venomous_dashboard.notes.ArticleWithChapterCount
	(*ArticleGetRequest)(nil),       // 13: venomous_dashboard.notes.ArticleGetRequest
	(*ArticleGetResponse)(nil),      // 14: venomous_dashboard.notes.ArticleGetResponse
	(*ArticleWithChapters)(nil),     // 15: venomous_dashboard.notes.ArticleWithChapters
	(*ArticleCreateRequest)(nil),    // 16: venomous_dashboard.notes.ArticleCreateRequest
	(*ArticleCreateResponse)(nil),   // 17: venomous_dashboard.notes.ArticleCreateResponse
	(*ArticleUpdateRequest)(nil),    // 18: venomous_dashboard.notes.ArticleUpdateRequest
	(*ArticleUpdateResponse)(nil),   // 19: venomous_dashboard.notes.ArticleUpdateResponse
	(*ArticleDeleteRequest)(nil),    // 20: venomous_dashboard.notes.ArticleDeleteRequest
	(*ArticleDeleteResponse)(nil),   // 21: venomous_dashboard.notes.ArticleDeleteResponse
	(*ChapterGetRequest)(nil),       // 22: venomous_dashboard.notes.ChapterGetRequest
	(*ChapterGetResponse)(nil),      // 23: venomous_dashboard.notes.ChapterGetResponse
	(*ChapterCreateRequest)(nil),    // 24: venomous_dashboard.notes.ChapterCreateRequest
	(*ChapterCreateResponse)(nil),   // 25: venomous_dashboard.notes.ChapterCreateResponse
	(*ChapterUpdateRequest)(nil),    // 26: venomous_dashboard.notes.ChapterUpdateRequest
	(*ChapterUpdateResponse)(nil),   // 27: venomous_dashboard.notes.ChapterUpdateResponse
	(*ChapterDeleteRequest)(nil),    // 28: venomous_dashboard.notes.ChapterDeleteRequest
	(*ChapterDeleteResponse)(nil),   // 29: venomous_dashboard.notes.ChapterDeleteResponse
	(*Memo)(nil),                    // 30: venomous_dashboard.notes.Memo
	(*__common.ApiError)(nil),       // 31: venomous_dashboard.common.ApiError
	(MemoColor)(0),                  // 32: venomous_dashboard.notes.MemoColor
	(*Article)(nil),                 // 33: venomous_dashboard.notes.Article
	(*ArticleChapter)(nil),          // 34: venomous_dashboard.notes.ArticleChapter
	(ArticleStatus)(0),              // 35: venomous_dashboard.notes.ArticleStatus
}
var file_notes_api_proto_depIdxs = []int32{
	30, // 0: venomous_dashboard.notes.MemoListResponse.data:type_name -> venomous_dashboard.notes.Memo
	31, // 1: venomous_dashboard.notes.MemoListResponse.error:type_name -> venomous_dashboard.common.ApiError
	30, // 2: venomous_dashboard.notes.MemoGetResponse.data:type_name -> venomous_dashboard.notes.Memo
	31, // 3: venomous_dashboard.notes.MemoGetResponse.error:type_name -> venomous_dashboard.common.ApiError
	32, // 4: venomous_dashboard.notes.MemoCreateRequest.color:type_name -> venomous_dashboard.notes.MemoColor
	30, // 5: venomous_dashboard.notes.MemoCreateResponse.data:type_name -> venomous_dashboard.notes.Memo
	31, // 6: venomous_dashboard.notes.MemoCreateResponse.error:type_name -> venomous_dashboard.common.ApiError
	32, // 7: venomous_dashboard.notes.MemoUpdateRequest.color:type_name -> venomous_dashboard.notes.MemoColor
	30, // 8: venomous_dashboard.notes.MemoUpdateResponse.data:type_name -> venomous_dashboard.notes.Memo
	31, // 9: venomous_dashboard.notes.MemoUpdateResponse.error:type_name -> venomous_dashboard.common.ApiError
	31, // 10: venomous_dashboard.notes.MemoDeleteResponse.error:type_name -> venomous_dashboard.common.ApiError
	12, // 11: venomous_dashboard.notes.ArticleListResponse.data:type_name -> venomous_dashboard.notes.ArticleWithChapterCount
	31, // 12: venomous_dashboard.notes.ArticleListResponse.error:type_name -> venomous_dashboard.common.ApiError
	33, // 13: venomous_dashboard.notes.ArticleWithChapterCount.article:type_name -> venomous_dashboard.notes.Article
	15, // 14: venomous_dashboard.notes.ArticleGetResponse.data:type_name -> venomous_dashboard.notes.ArticleWithChapters
	31, // 15: venomous_dashboard.notes.ArticleGetResponse.error:type_name -> venomous_dashboard.common.ApiError
	33, // 16: venomous_dashboard.notes.ArticleWithChapters.article:type_name -> venomous_dashboard.notes.Article
	34, // 17: venomous_dashboard.notes.ArticleWithChapters.chapters:type_name -> venomous_dashboard.notes.ArticleChapter
	33, // 18: venomous_dashboard.notes.ArticleCreateResponse.data:type_name -> venomous_dashboard.notes.Article
	31, // 19: venomous_dashboard.notes.ArticleCreateResponse.error:type_name -> venomous_dashboard.common.ApiError
	35, // 20: venomous_dashboard.notes.ArticleUpdateRequest.status:type_name -> venomous_dashboard.notes.ArticleStatus
	33, // 21: venomous_dashboard.notes.ArticleUpdateResponse.data:type_name -> venomous_dashboard.notes.Article
	31, // 22: venomous_dashboard.notes.ArticleUpdateResponse.error:type_name -> venomous_dashboard.common.ApiError
	31, // 23: venomous_dashboard.notes.ArticleDeleteResponse.error:type_name -> venomous_dashboard.common.ApiError
	34, // 24: venomous_dashboard.notes.ChapterGetResponse.data:type_name -> venomous_dashboard.notes.ArticleChapter
	31, // 25: venomous_dashboard.notes.ChapterGetResponse.error:type_name -> venomous_dashboard.common.ApiError
	34, // 26: venomous_dashboard.notes.ChapterCreateResponse.data:type_name -> venomous_dashboard.notes.ArticleChapter
	31, // 27: venomous_dashboard.notes.ChapterCreateResponse.error:type_name -> venomous_dashboard.common.ApiError
	34, // 28: venomous_dashboard.notes.ChapterUpdateResponse.data:type_name -> venomous_dashboard.notes.ArticleChapter
	31, // 29: venomous_dashboard.notes.ChapterUpdateResponse.error:type_name -> venomous_dashboard.common.ApiError
	31, // 30: venomous_dashboard.notes.ChapterDeleteResponse.error:type_name -> venomous_dashboard.common.ApiError
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_notes_api_proto_init() }
func file_notes_api_proto_init() {
	if File_notes_api_proto != nil {
		return
	}
	file_notes_interface_proto_init()
	file_notes_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[11].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[14].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[16].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[17].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[18].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[19].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[21].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[23].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[25].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[26].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[27].OneofWrappers = []any{}
	file_notes_api_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notes_api_proto_rawDesc), len(file_notes_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notes_api_proto_goTypes,
		DependencyIndexes: file_notes_api_proto_depIdxs,
		MessageInfos:      file_notes_api_proto_msgTypes,
	}.Build()
	File_notes_api_proto = out.File
	file_notes_api_proto_goTypes = nil
	file_notes_api_proto_depIdxs = nil
}
