// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: notes/interface.proto

package notes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoColor int32

const (
	MemoColor_YELLOW MemoColor = 0
	MemoColor_GREEN  MemoColor = 1
	MemoColor_BLUE   MemoColor = 2
	MemoColor_PINK   MemoColor = 3
	MemoColor_PURPLE MemoColor = 4
	MemoColor_GRAY   MemoColor = 5
)

// Enum value maps for MemoColor.
var (
	MemoColor_name = map[int32]string{
		0: "YELLOW",
		1: "GREEN",
		2: "BLUE",
		3: "PINK",
		4: "PURPLE",
		5: "GRAY",
	}
	MemoColor_value = map[string]int32{
		"YELLOW": 0,
		"GREEN":  1,
		"BLUE":   2,
		"PINK":   3,
		"PURPLE": 4,
		"GRAY":   5,
	}
)

func (x MemoColor) Enum() *MemoColor {
	p := new(MemoColor)
	*p = x
	return p
}

func (x MemoColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoColor) Descriptor() protoreflect.EnumDescriptor {
	return file_notes_interface_proto_enumTypes[0].Descriptor()
}

func (MemoColor) Type() protoreflect.EnumType {
	return &file_notes_interface_proto_enumTypes[0]
}

func (x MemoColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoColor.Descriptor instead.
func (MemoColor) EnumDescriptor() ([]byte, []int) {
	return file_notes_interface_proto_rawDescGZIP(), []int{0}
}

type ArticleStatus int32

const (
	ArticleStatus_DRAFT     ArticleStatus = 0
	ArticleStatus_PUBLISHED ArticleStatus = 1
	ArticleStatus_ARCHIVED  ArticleStatus = 2
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	ArticleStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notes_interface_proto_enumTypes[1].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_notes_interface_proto_enumTypes[1]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_notes_interface_proto_rawDescGZIP(), []int{1}
}

type Memo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Color         MemoColor              `protobuf:"varint,4,opt,name=color,proto3,enum=venomous_dashboard.notes.MemoColor" json:"color,omitempty"`
	IsPinned      bool                   `protobuf:"varint,5,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_notes_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_notes_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_notes_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Memo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Memo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memo) GetColor() MemoColor {
	if x != nil {
		return x.Color
	}
	return MemoColor_YELLOW
}

func (x *Memo) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Memo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Memo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Memo) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Category      *string                `protobuf:"bytes,6,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Status        ArticleStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=venomous_dashboard.notes.ArticleStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_notes_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_notes_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_notes_interface_proto_rawDescGZIP(), []int{1}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Article) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *Article) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Article) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_DRAFT
}

func (x *Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Article) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type ArticleChapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ChapterNumber int32                  `protobuf:"varint,5,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	WordCount     int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleChapter) Reset() {
	*x = ArticleChapter{}
	mi := &file_notes_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleChapter) ProtoMessage() {}

func (x *ArticleChapter) ProtoReflect() protoreflect.Message {
	mi := &file_notes_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleChapter.ProtoReflect.Descriptor instead.
func (*ArticleChapter) Descriptor() ([]byte, []int) {
	return file_notes_interface_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleChapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArticleChapter) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleChapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleChapter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleChapter) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *ArticleChapter) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ArticleChapter) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ArticleChapter) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ArticleChapter) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

var File_notes_interface_proto protoreflect.FileDescriptor

const file_notes_interface_proto_rawDesc = "" +
	"\n" +
	"\x15notes/interface.proto\x12\x18venomous_dashboard.notes\"\x92\x02\n" +
	"\x04Memo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\x05color\x18\x04 \x01(\x0e2#.venomous_dashboard.notes.MemoColorR\x05color\x12\x1b\n" +
	"\tis_pinned\x18\x05 \x01(\bR\bisPinned\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at\"\xa0\x03\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tH\x01R\rcoverImageUrl\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x06 \x01(\tH\x02R\bcategory\x88\x01\x01\x12?\n" +
	"\x06status\x18\a \x01(\x0e2'.venomous_dashboard.notes.ArticleStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\tH\x03R\tdeletedAt\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_cover_image_urlB\v\n" +
	"\t_categoryB\r\n" +
	"\v_deleted_at\"\xa6\x02\n" +
	"\x0eArticleChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12%\n" +
	"\x0echapter_number\x18\x05 \x01(\x05R\rchapterNumber\x12\x1d\n" +
	"\n" +
	"word_count\x18\x06 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at*L\n" +
	"\tMemoColor\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02\x12\b\n" +
	"\x04PINK\x10\x03\x12\n" +
	"\n" +
	"\x06PURPLE\x10\x04\x12\b\n" +
	"\x04GRAY\x10\x05*7\n" +
	"\rArticleStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x02BPZNgithub.com/venomous-dashboard/api-gateway/internal/types/proto_generated/notesb\x06proto3"

var (
	file_notes_interface_proto_rawDescOnce sync.Once
	file_notes_interface_proto_rawDescData []byte
)

func file_notes_interface_proto_rawDescGZIP() []byte {
	file_notes_interface_proto_rawDescOnce.Do(func() {
		file_notes_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notes_interface_proto_rawDesc), len(file_notes_interface_proto_rawDesc)))
	})
	return file_notes_interface_proto_rawDescData
}

var file_notes_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notes_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notes_interface_proto_goTypes = []any{
	(MemoColor)(0),         // 0: venomous_dashboard.notes.MemoColor
	(ArticleStatus)(0),     // 1: venomous_dashboard.notes.ArticleStatus
	(*Memo)(nil),           // 2: venomous_dashboard.notes.Memo
	(*Article)(nil),        // 3: venomous_dashboard.notes.Article
	(*ArticleChapter)(nil), // 4: venomous_dashboard.notes.ArticleChapter
}
var file_notes_interface_proto_depIdxs = []int32{
	0, // 0: venomous_dashboard.notes.Memo.color:type_name -> venomous_dashboard.notes.MemoColor
	1, // 1: venomous_dashboard.notes.Article.status:type_name -> venomous_dashboard.notes.ArticleStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notes_interface_proto_init() }
func file_notes_interface_proto_init() {
	if File_notes_interface_proto != nil {
		return
	}
	file_notes_interface_proto_msgTypes[0].OneofWrappers = []any{}
	file_notes_interface_proto_msgTypes[1].OneofWrappers = []any{}
	file_notes_interface_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notes_interface_proto_rawDesc), len(file_notes_interface_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notes_interface_proto_goTypes,
		DependencyIndexes: file_notes_interface_proto_depIdxs,
		EnumInfos:         file_notes_interface_proto_enumTypes,
		MessageInfos:      file_notes_interface_proto_msgTypes,
	}.Build()
	File_notes_interface_proto = out.File
	file_notes_interface_proto_goTypes = nil
	file_notes_interface_proto_depIdxs = nil
}
