export const VALIDATION_MESSAGE_I18N_KEYS = {
  // Common
  REQUIRED: "REQUIRED",
  INVALID: "INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_INVALID: "TOKEN_INVALID",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONTENT_REQUIRED: "CONTENT_REQUIRED",
  INVALID_INPUT: "INVALID_INPUT",
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NO_FIELDS_TO_UPDATE: "NO_FIELDS_TO_UPDATE",
  UPDATE_FAILED: "UPDATE_FAILED",

  // Auth - User
  NAME_TOO_SHORT: "NAME_TOO_SHORT",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  NAME_INVALID_CHARS: "NAME_INVALID_CHARS",
  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  EMAIL_INVALID: "EMAIL_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_WEAK: "PASSWORD_WEAK",
  CONFIRM_PASSWORD_MISMATCH: "CONFIRM_PASSWORD_MISMATCH",

  // Notes - Memos
  MEMO_NOT_FOUND: "MEMO_NOT_FOUND",
  MEMO_CONTENT_REQUIRED: "MEMO_CONTENT_REQUIRED",
  MEMO_COLOR_INVALID: "MEMO_COLOR_INVALID",

  // Notes - Articles
  ARTICLE_NOT_FOUND: "ARTICLE_NOT_FOUND",
  ARTICLE_TITLE_REQUIRED: "ARTICLE_TITLE_REQUIRED",
  ARTICLE_COVER_URL_INVALID: "ARTICLE_COVER_URL_INVALID",
  ARTICLE_STATUS_INVALID: "ARTICLE_STATUS_INVALID",

  // Notes - Chapters
  CHAPTER_NOT_FOUND: "CHAPTER_NOT_FOUND",
  CHAPTER_TITLE_REQUIRED: "CHAPTER_TITLE_REQUIRED",
  CHAPTER_CONTENT_REQUIRED: "CHAPTER_CONTENT_REQUIRED",
  CHAPTER_NUMBER_INVALID: "CHAPTER_NUMBER_INVALID",
  CHAPTER_WORD_COUNT_INVALID: "CHAPTER_WORD_COUNT_INVALID",
} as const;
