export const VALIDATION_MESSAGE_I18N_KEYS = {
  REQUIRED: "REQUIRED",
  INVALID: "INVALID",

  NAME_TOO_SHORT: "NAME_TOO_SHORT",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  NAME_INVALID_CHARS: "NAME_INVALID_CHARS",

  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  EMAIL_INVALID: "EMAIL_INVALID",

  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_WEAK: "PASSWORD_WEAK",
  CONFIRM_PASSWORD_MISMATCH: "CONFIRM_PASSWORD_MISMATCH",
} as const;
