// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: auth/api.proto

/* eslint-disable */
import type { TApiError } from "./common.types";
import type { TAuthTokenInfo, TUser } from "./interface.types";

export interface TAuthSignupRequest {
  email: string;
  password: string;
  name: string;
}

export interface TAuthSignupResponse {
  success: boolean;
  data?: TAuthSignupData | undefined;
  error?: TApiError | undefined;
}

export interface TAuthSignupData {
  token: string;
  user: TUser | undefined;
  createdAt: string;
}

export interface TAuthSigninRequest {
  email: string;
  password: string;
}

export interface TAuthSigninResponse {
  success: boolean;
  data?: TAuthSigninData | undefined;
  error?: TApiError | undefined;
}

export interface TAuthSigninData {
  token: string;
  user: TUser | undefined;
  lastLogin: string;
}

export interface TAuthLogoutRequest {
  token: string;
}

export interface TAuthLogoutResponse {
  success: boolean;
  error?: TApiError | undefined;
}

export interface TAuthTokenVerifyRequest {
  token: string;
}

export interface TAuthTokenVerifyResponse {
  success: boolean;
  data?: TAuthTokenInfo | undefined;
  error?: TApiError | undefined;
}

export interface TAuthTokenInfoRequest {
  token: string;
}

export interface TAuthTokenInfoResponse {
  success: boolean;
  data?: TAuthTokenInfo | undefined;
  error?: TApiError | undefined;
}

export interface TAuthTokenRefreshRequest {
  token: string;
}

export interface TAuthTokenRefreshResponse {
  success: boolean;
  data?: TAuthTokenRefreshData | undefined;
  error?: TApiError | undefined;
}

export interface TAuthTokenRefreshData {
  token: string;
  expiresAt: number;
}

/** No fields needed - user identified by JWT token */
export interface TUserGetProfileRequest {}

export interface TUserGetProfileResponse {
  success: boolean;
  data?: TUser | undefined;
  error?: TApiError | undefined;
}

export interface TUserUpdateProfileRequest {
  name?: string | undefined;
  avatarPath?: string | undefined;
}

export interface TUserUpdateProfileResponse {
  success: boolean;
  data?: TUser | undefined;
  error?: TApiError | undefined;
}
