// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: auth/common.proto

/* eslint-disable */

export interface TApiError {
  code: string;
  message: string;
}
