// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: auth/interface.proto

/* eslint-disable */

export interface TRole {
  id: string;
  name: string;
  description?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TUser {
  id: string;
  email: string;
  name: string;
  roleId: string;
  avatarPath?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TAuthUser {
  id: string;
  userId: string;
  email: string;
  passwordHash: string;
  emailVerified: boolean;
  lastLogin?: string | undefined;
  loginFailureCount: number;
  isLoginLocked: boolean;
  deletedAt?: string | undefined;
}

export interface TUserProfile {
  /** Fields from User table */
  id: string;
  email: string;
  name: string;
  roleId: string;
  avatarPath?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  /** Fields from AuthUser table */
  emailVerified: boolean;
  lastLogin?: string | undefined;
  loginFailureCount: number;
  isLoginLocked: boolean;
  /** Fields from Role table */
  roleName: string;
}

export interface TAuthToken {
  token: string;
  expiresAt: string;
  issuedAt: string;
}

export interface TAuthTokenInfo {
  valid: boolean;
  userId: string;
  email: string;
  name: string;
  role: string;
  expiresAt: number;
  issuedAt: number;
}
