// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: _common/interface.proto

package __common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file___common_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file___common_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file___common_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ApiError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File___common_interface_proto protoreflect.FileDescriptor

const file___common_interface_proto_rawDesc = "" +
	"\n" +
	"\x17_common/interface.proto\x12\x19venomous_dashboard.common\"8\n" +
	"\bApiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBRZPgithub.com/venomous-dashboard/api-gateway/internal/types/proto_generated/_commonb\x06proto3"

var (
	file___common_interface_proto_rawDescOnce sync.Once
	file___common_interface_proto_rawDescData []byte
)

func file___common_interface_proto_rawDescGZIP() []byte {
	file___common_interface_proto_rawDescOnce.Do(func() {
		file___common_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___common_interface_proto_rawDesc), len(file___common_interface_proto_rawDesc)))
	})
	return file___common_interface_proto_rawDescData
}

var file___common_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file___common_interface_proto_goTypes = []any{
	(*ApiError)(nil), // 0: venomous_dashboard.common.ApiError
}
var file___common_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file___common_interface_proto_init() }
func file___common_interface_proto_init() {
	if File___common_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___common_interface_proto_rawDesc), len(file___common_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___common_interface_proto_goTypes,
		DependencyIndexes: file___common_interface_proto_depIdxs,
		MessageInfos:      file___common_interface_proto_msgTypes,
	}.Build()
	File___common_interface_proto = out.File
	file___common_interface_proto_goTypes = nil
	file___common_interface_proto_depIdxs = nil
}
