services:
  # ====================================================================================================
  # Application: dashboard
  # ====================================================================================================
  dashboard:
    container_name: dashboard
    build:
      context: ../../dashboard
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../../dashboard:/app
    networks:
      - venomous-network

  # ====================================================================================================
  # API Gateway: api-gateway
  # ====================================================================================================
  api-gateway:
    container_name: api-gateway
    build:
      context: ../../services/api-gateway
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../../services/api-gateway:/app
    networks:
      - venomous-network
    depends_on:
      - auth
      # - notes
      # - medias
      # - workflows

  # ====================================================================================================
  # Headless Service: auth
  # ====================================================================================================
  auth:
    container_name: auth
    build:
      context: ../../services/auth
      dockerfile: docker/Dockerfile.dev
    environment:
      DATABASE_URL: "postgresql://venomous_dashboard_db:venomous@db:5432/venomous_auth_db"
      RUST_LOG: info
    volumes:
      - ../../services/auth:/app
    networks:
      - venomous-network
    depends_on:
      - db

  # ====================================================================================================
  # Headless Service: notes
  # ====================================================================================================
  notes:
    container_name: notes
    build:
      context: ../../services/notes
      dockerfile: Dockerfile.dev
    volumes:
      - ../../services/notes:/app
    networks:
      - venomous-network

  # ====================================================================================================
  # Headless Service: medias
  # ====================================================================================================
  medias:
    container_name: medias
    build:
      context: ../../services/medias
      dockerfile: Dockerfile.dev
    volumes:
      - ../../services/medias:/app
    networks:
      - venomous-network

  # ====================================================================================================
  # Headless Service: workflows
  # ====================================================================================================
  workflows:
    container_name: workflows
    build:
      context: ../../services/workflows
      dockerfile: Dockerfile.dev
    volumes:
      - ../../services/workflows:/app
    networks:
      - venomous-network

  # ====================================================================================================
  # Database: db
  # ====================================================================================================
  db:
    container_name: db
    image: postgres:15
    ports:
      - "9100:5432"
    environment:
      POSTGRES_DB: venomous_dashboard_db
      POSTGRES_USER: venomous_dashboard_db
      POSTGRES_PASSWORD: venomous
    volumes:
      - venomous-db-data:/var/lib/postgresql/data
      - ../database/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    networks:
      - venomous-network

  # ====================================================================================================
  # Cache: redis
  # ====================================================================================================
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "9200:6379"
    networks:
      - venomous-network

  # ====================================================================================================
  # Storage: minio
  # ====================================================================================================
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9300:9000"
      - "9301:9001"
    environment:
      MINIO_ROOT_USER: venomous_dashboard_minio
      MINIO_ROOT_PASSWORD: venomous
    volumes:
      - venomous-minio-data:/data
    networks:
      - venomous-network

networks:
  venomous-network:
    driver: bridge

volumes:
  venomous-db-data:
  venomous-minio-data:
