// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes/api.proto

/* eslint-disable */
import type { TApiError } from "../_common/interface.types";
import type { TArticle, TArticleChapter, TArticleStatus, TMemo, TMemoColor } from "./interface.types";

/** No fields needed - user identified by JWT token */
export interface TMemoListRequest {
}

export interface TMemoListResponse {
  success: boolean;
  data: TMemo[];
  error?: TApiError | undefined;
}

export interface TMemoGetRequest {
  id: string;
}

export interface TMemoGetResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoCreateRequest {
  content: string;
  color: TMemoColor;
  isPinned: boolean;
}

export interface TMemoCreateResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoUpdateRequest {
  id: string;
  content?: string | undefined;
  color?: TMemoColor | undefined;
  isPinned?: boolean | undefined;
}

export interface TMemoUpdateResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoDeleteRequest {
  id: string;
}

export interface TMemoDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}

/** No fields needed - user identified by JWT token */
export interface TArticleListRequest {
}

export interface TArticleListResponse {
  success: boolean;
  data: TArticleWithChapterCount[];
  error?: TApiError | undefined;
}

export interface TArticleWithChapterCount {
  article: TArticle | undefined;
  chapterCount: number;
}

export interface TArticleGetRequest {
  id: string;
}

export interface TArticleGetResponse {
  success: boolean;
  data?: TArticleWithChapters | undefined;
  error?: TApiError | undefined;
}

export interface TArticleWithChapters {
  article: TArticle | undefined;
  chapters: TArticleChapter[];
}

export interface TArticleCreateRequest {
  title: string;
  description?: string | undefined;
  category?: string | undefined;
  coverImageUrl?: string | undefined;
}

export interface TArticleCreateResponse {
  success: boolean;
  data?: TArticle | undefined;
  error?: TApiError | undefined;
}

export interface TArticleUpdateRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
  coverImageUrl?: string | undefined;
  status?: TArticleStatus | undefined;
}

export interface TArticleUpdateResponse {
  success: boolean;
  data?: TArticle | undefined;
  error?: TApiError | undefined;
}

export interface TArticleDeleteRequest {
  id: string;
}

export interface TArticleDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}

export interface TChapterGetRequest {
  articleId: string;
  chapterId: string;
}

export interface TChapterGetResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterCreateRequest {
  articleId: string;
  title: string;
  content: string;
  chapterNumber: number;
  wordCount: number;
}

export interface TChapterCreateResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterUpdateRequest {
  articleId: string;
  chapterId: string;
  title?: string | undefined;
  content?: string | undefined;
  wordCount?: number | undefined;
}

export interface TChapterUpdateResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterDeleteRequest {
  articleId: string;
  chapterId: string;
}

export interface TChapterDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}
