// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes/api.proto

/* eslint-disable */
import type { TApiError } from "../_common/interface.types";
import type { TArticle, TArticleChapter, TArticleStatus, TMemo } from "./interface.types";

export interface TMemoListRequest {
  /** Pagination */
  page?:
    | number
    | undefined;
  /** Items per page (default: 20, max: 100) */
  pageSize?:
    | number
    | undefined;
  /** Filtering */
  color?:
    | string
    | undefined;
  /** Filter by pinned status */
  isPinned?:
    | boolean
    | undefined;
  /** Search in content (fuzzy match) */
  search?:
    | string
    | undefined;
  /** Sorting */
  sortBy?:
    | string
    | undefined;
  /** Sort order: asc, desc (default: desc) */
  sortOrder?: string | undefined;
}

export interface TMemoListResponse {
  success: boolean;
  data: TMemo[];
  error?:
    | TApiError
    | undefined;
  /** Pagination metadata */
  meta?: TPaginationMeta | undefined;
}

export interface TMemoGetRequest {
  id: string;
}

export interface TMemoGetResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoCreateRequest {
  content: string;
  /** Hex color string (default: "#FFF9C4") */
  color?:
    | string
    | undefined;
  /** Default: false */
  isPinned?: boolean | undefined;
}

export interface TMemoCreateResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoUpdateRequest {
  id: string;
  content?:
    | string
    | undefined;
  /** Hex color string */
  color?: string | undefined;
  isPinned?: boolean | undefined;
}

export interface TMemoUpdateResponse {
  success: boolean;
  data?: TMemo | undefined;
  error?: TApiError | undefined;
}

export interface TMemoDeleteRequest {
  id: string;
}

export interface TMemoDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}

export interface TArticleListRequest {
  /** Pagination */
  page?:
    | number
    | undefined;
  /** Items per page (default: 20, max: 100) */
  pageSize?:
    | number
    | undefined;
  /** Filtering */
  status?:
    | TArticleStatus
    | undefined;
  /** Filter by category */
  category?:
    | string
    | undefined;
  /** Search in title and description */
  search?:
    | string
    | undefined;
  /** Sorting */
  sortBy?:
    | string
    | undefined;
  /** Sort order: asc, desc (default: desc) */
  sortOrder?: string | undefined;
}

export interface TArticleListResponse {
  success: boolean;
  data: TArticleWithChapterCount[];
  error?:
    | TApiError
    | undefined;
  /** Pagination metadata */
  meta?: TPaginationMeta | undefined;
}

export interface TArticleWithChapterCount {
  article: TArticle | undefined;
  chapterCount: number;
}

export interface TArticleGetRequest {
  id: string;
}

export interface TArticleGetResponse {
  success: boolean;
  data?: TArticleWithChapters | undefined;
  error?: TApiError | undefined;
}

export interface TArticleWithChapters {
  article: TArticle | undefined;
  chapters: TArticleChapter[];
}

export interface TArticleCreateRequest {
  title: string;
  description?: string | undefined;
  category?: string | undefined;
  coverImageUrl?: string | undefined;
}

export interface TArticleCreateResponse {
  success: boolean;
  data?: TArticle | undefined;
  error?: TApiError | undefined;
}

export interface TArticleUpdateRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
  coverImageUrl?: string | undefined;
  status?: TArticleStatus | undefined;
}

export interface TArticleUpdateResponse {
  success: boolean;
  data?: TArticle | undefined;
  error?: TApiError | undefined;
}

export interface TArticleDeleteRequest {
  id: string;
}

export interface TArticleDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}

export interface TChapterGetRequest {
  articleId: string;
  chapterId: string;
}

export interface TChapterGetResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterCreateRequest {
  articleId: string;
  title: string;
  content: string;
  chapterNumber: number;
  /** Optional, auto-calculated from content */
  wordCount?: number | undefined;
}

export interface TChapterCreateResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterUpdateRequest {
  articleId: string;
  chapterId: string;
  title?: string | undefined;
  content?:
    | string
    | undefined;
  /** Support reordering */
  chapterNumber?:
    | number
    | undefined;
  /** Optional, auto-calculated from content */
  wordCount?: number | undefined;
}

export interface TChapterUpdateResponse {
  success: boolean;
  data?: TArticleChapter | undefined;
  error?: TApiError | undefined;
}

export interface TChapterDeleteRequest {
  articleId: string;
  chapterId: string;
}

export interface TChapterDeleteResponse {
  success: boolean;
  error?: TApiError | undefined;
}

export interface TPaginationMeta {
  /** Total number of items */
  total: number;
  /** Current page number */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total number of pages */
  totalPages: number;
}
