// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes/interface.proto

/* eslint-disable */

export enum TArticleStatus {
  DRAFT = 0,
  PUBLISHED = 1,
  ARCHIVED = 2,
  UNRECOGNIZED = -1,
}

export interface TMemo {
  id: string;
  userId: string;
  content: string;
  /** Hex color string (e.g., "#FFF9C4") */
  color: string;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TArticle {
  id: string;
  userId: string;
  title: string;
  description?: string | undefined;
  coverImageUrl?: string | undefined;
  category?: string | undefined;
  status: TArticleStatus;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TArticleChapter {
  id: string;
  articleId: string;
  title: string;
  content: string;
  chapterNumber: number;
  wordCount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}
