// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes/interface.proto

/* eslint-disable */

export enum TMemoColor {
  YELLOW = 0,
  GREEN = 1,
  BLUE = 2,
  PINK = 3,
  PURPLE = 4,
  GRAY = 5,
  UNRECOGNIZED = -1,
}

export enum TArticleStatus {
  DRAFT = 0,
  PUBLISHED = 1,
  ARCHIVED = 2,
  UNRECOGNIZED = -1,
}

export interface TMemo {
  id: string;
  userId: string;
  content: string;
  color: TMemoColor;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TArticle {
  id: string;
  userId: string;
  title: string;
  description?: string | undefined;
  coverImageUrl?: string | undefined;
  category?: string | undefined;
  status: TArticleStatus;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface TArticleChapter {
  id: string;
  articleId: string;
  title: string;
  content: string;
  chapterNumber: number;
  wordCount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}
