# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies, including nodemon if it's in devDependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Run the app with nodemon for hot-reloading
# The port will be internal to docker
CMD ["npx", "nodemon", "index.js"]
