# Use an official Golang runtime as a parent image
FROM golang:1.20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy go.mod and go.sum to download dependencies
COPY go.mod go.sum ./

# Download any needed modules
RUN go mod download

# Install air for hot-reloading
RUN go install github.com/cosmtrek/air@latest

# Copy the rest of the application's code
COPY . .

# Make port 8080 available
EXPOSE 8080

# Run the app with air for hot-reloading
CMD ["air", "-c", ".air.toml"]
