// @generated
// This file is @generated by prost-build.
// ====================================================================================================
// Common Types (Shared across all services)
// ====================================================================================================

#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct ApiError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
