// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: auth/api.proto

package auth

import (
	__common "github.com/venomous-dashboard/api-gateway/internal/types/proto_generated/_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignupRequest) Reset() {
	*x = AuthSignupRequest{}
	mi := &file_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignupRequest) ProtoMessage() {}

func (x *AuthSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignupRequest.ProtoReflect.Descriptor instead.
func (*AuthSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *AuthSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthSignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthSignupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuthSignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *AuthSignupData        `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignupResponse) Reset() {
	*x = AuthSignupResponse{}
	mi := &file_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignupResponse) ProtoMessage() {}

func (x *AuthSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignupResponse.ProtoReflect.Descriptor instead.
func (*AuthSignupResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{1}
}

func (x *AuthSignupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthSignupResponse) GetData() *AuthSignupData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthSignupResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthSignupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignupData) Reset() {
	*x = AuthSignupData{}
	mi := &file_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignupData) ProtoMessage() {}

func (x *AuthSignupData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignupData.ProtoReflect.Descriptor instead.
func (*AuthSignupData) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *AuthSignupData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthSignupData) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthSignupData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuthSigninRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSigninRequest) Reset() {
	*x = AuthSigninRequest{}
	mi := &file_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSigninRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSigninRequest) ProtoMessage() {}

func (x *AuthSigninRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSigninRequest.ProtoReflect.Descriptor instead.
func (*AuthSigninRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthSigninRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthSigninRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthSigninResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *AuthSigninData        `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSigninResponse) Reset() {
	*x = AuthSigninResponse{}
	mi := &file_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSigninResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSigninResponse) ProtoMessage() {}

func (x *AuthSigninResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSigninResponse.ProtoReflect.Descriptor instead.
func (*AuthSigninResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *AuthSigninResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthSigninResponse) GetData() *AuthSigninData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthSigninResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthSigninData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LastLogin     string                 `protobuf:"bytes,3,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSigninData) Reset() {
	*x = AuthSigninData{}
	mi := &file_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSigninData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSigninData) ProtoMessage() {}

func (x *AuthSigninData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSigninData.ProtoReflect.Descriptor instead.
func (*AuthSigninData) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *AuthSigninData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthSigninData) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthSigninData) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type AuthLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutRequest) Reset() {
	*x = AuthLogoutRequest{}
	mi := &file_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutRequest) ProtoMessage() {}

func (x *AuthLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutRequest.ProtoReflect.Descriptor instead.
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *AuthLogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutResponse) Reset() {
	*x = AuthLogoutResponse{}
	mi := &file_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutResponse) ProtoMessage() {}

func (x *AuthLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutResponse.ProtoReflect.Descriptor instead.
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{7}
}

func (x *AuthLogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthLogoutResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthTokenVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenVerifyRequest) Reset() {
	*x = AuthTokenVerifyRequest{}
	mi := &file_auth_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenVerifyRequest) ProtoMessage() {}

func (x *AuthTokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *AuthTokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthTokenVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *AuthTokenInfo         `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenVerifyResponse) Reset() {
	*x = AuthTokenVerifyResponse{}
	mi := &file_auth_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenVerifyResponse) ProtoMessage() {}

func (x *AuthTokenVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenVerifyResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenVerifyResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{9}
}

func (x *AuthTokenVerifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthTokenVerifyResponse) GetData() *AuthTokenInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthTokenVerifyResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenInfoRequest) Reset() {
	*x = AuthTokenInfoRequest{}
	mi := &file_auth_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenInfoRequest) ProtoMessage() {}

func (x *AuthTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{10}
}

func (x *AuthTokenInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthTokenInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *AuthTokenInfo         `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenInfoResponse) Reset() {
	*x = AuthTokenInfoResponse{}
	mi := &file_auth_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenInfoResponse) ProtoMessage() {}

func (x *AuthTokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenInfoResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{11}
}

func (x *AuthTokenInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthTokenInfoResponse) GetData() *AuthTokenInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthTokenInfoResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthTokenRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenRefreshRequest) Reset() {
	*x = AuthTokenRefreshRequest{}
	mi := &file_auth_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRefreshRequest) ProtoMessage() {}

func (x *AuthTokenRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRefreshRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenRefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{12}
}

func (x *AuthTokenRefreshRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthTokenRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *AuthTokenRefreshData  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenRefreshResponse) Reset() {
	*x = AuthTokenRefreshResponse{}
	mi := &file_auth_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRefreshResponse) ProtoMessage() {}

func (x *AuthTokenRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRefreshResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenRefreshResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{13}
}

func (x *AuthTokenRefreshResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthTokenRefreshResponse) GetData() *AuthTokenRefreshData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthTokenRefreshResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type AuthTokenRefreshData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenRefreshData) Reset() {
	*x = AuthTokenRefreshData{}
	mi := &file_auth_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenRefreshData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRefreshData) ProtoMessage() {}

func (x *AuthTokenRefreshData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRefreshData.ProtoReflect.Descriptor instead.
func (*AuthTokenRefreshData) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{14}
}

func (x *AuthTokenRefreshData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthTokenRefreshData) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UserGetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProfileRequest) Reset() {
	*x = UserGetProfileRequest{}
	mi := &file_auth_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProfileRequest) ProtoMessage() {}

func (x *UserGetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProfileRequest.ProtoReflect.Descriptor instead.
func (*UserGetProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{15}
}

type UserGetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *UserProfile           `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProfileResponse) Reset() {
	*x = UserGetProfileResponse{}
	mi := &file_auth_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProfileResponse) ProtoMessage() {}

func (x *UserGetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProfileResponse.ProtoReflect.Descriptor instead.
func (*UserGetProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{16}
}

func (x *UserGetProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserGetProfileResponse) GetData() *UserProfile {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserGetProfileResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

type UserUpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AvatarPath    *string                `protobuf:"bytes,2,opt,name=avatar_path,json=avatarPath,proto3,oneof" json:"avatar_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateProfileRequest) Reset() {
	*x = UserUpdateProfileRequest{}
	mi := &file_auth_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProfileRequest) ProtoMessage() {}

func (x *UserUpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{17}
}

func (x *UserUpdateProfileRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserUpdateProfileRequest) GetAvatarPath() string {
	if x != nil && x.AvatarPath != nil {
		return *x.AvatarPath
	}
	return ""
}

type UserUpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *User                  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *__common.ApiError     `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateProfileResponse) Reset() {
	*x = UserUpdateProfileResponse{}
	mi := &file_auth_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProfileResponse) ProtoMessage() {}

func (x *UserUpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_proto_rawDescGZIP(), []int{18}
}

func (x *UserUpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserUpdateProfileResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserUpdateProfileResponse) GetError() *__common.ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_auth_api_proto protoreflect.FileDescriptor

const file_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x0eauth/api.proto\x12\x17venomous_dashboard.auth\x1a\x17_common/interface.proto\x1a\x14auth/interface.proto\"Y\n" +
	"\x11AuthSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xc3\x01\n" +
	"\x12AuthSignupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x04data\x18\x02 \x01(\v2'.venomous_dashboard.auth.AuthSignupDataH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"x\n" +
	"\x0eAuthSignupData\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.venomous_dashboard.auth.UserR\x04user\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"E\n" +
	"\x11AuthSigninRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc3\x01\n" +
	"\x12AuthSigninResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x04data\x18\x02 \x01(\v2'.venomous_dashboard.auth.AuthSigninDataH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"x\n" +
	"\x0eAuthSigninData\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.venomous_dashboard.auth.UserR\x04user\x12\x1d\n" +
	"\n" +
	"last_login\x18\x03 \x01(\tR\tlastLogin\")\n" +
	"\x11AuthLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"x\n" +
	"\x12AuthLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\x05error\x18\x02 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\".\n" +
	"\x16AuthTokenVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc7\x01\n" +
	"\x17AuthTokenVerifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\x04data\x18\x02 \x01(\v2&.venomous_dashboard.auth.AuthTokenInfoH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\",\n" +
	"\x14AuthTokenInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc5\x01\n" +
	"\x15AuthTokenInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\x04data\x18\x02 \x01(\v2&.venomous_dashboard.auth.AuthTokenInfoH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"/\n" +
	"\x17AuthTokenRefreshRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xcf\x01\n" +
	"\x18AuthTokenRefreshResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12F\n" +
	"\x04data\x18\x02 \x01(\v2-.venomous_dashboard.auth.AuthTokenRefreshDataH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"K\n" +
	"\x14AuthTokenRefreshData\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x17\n" +
	"\x15UserGetProfileRequest\"\xc4\x01\n" +
	"\x16UserGetProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12=\n" +
	"\x04data\x18\x02 \x01(\v2$.venomous_dashboard.auth.UserProfileH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"r\n" +
	"\x18UserUpdateProfileRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12$\n" +
	"\vavatar_path\x18\x02 \x01(\tH\x01R\n" +
	"avatarPath\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_avatar_path\"\xc0\x01\n" +
	"\x19UserUpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.venomous_dashboard.auth.UserH\x00R\x04data\x88\x01\x01\x12>\n" +
	"\x05error\x18\x03 \x01(\v2#.venomous_dashboard.common.ApiErrorH\x01R\x05error\x88\x01\x01B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_errorBOZMgithub.com/venomous-dashboard/api-gateway/internal/types/proto_generated/authb\x06proto3"

var (
	file_auth_api_proto_rawDescOnce sync.Once
	file_auth_api_proto_rawDescData []byte
)

func file_auth_api_proto_rawDescGZIP() []byte {
	file_auth_api_proto_rawDescOnce.Do(func() {
		file_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_api_proto_rawDesc), len(file_auth_api_proto_rawDesc)))
	})
	return file_auth_api_proto_rawDescData
}

var file_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_auth_api_proto_goTypes = []any{
	(*AuthSignupRequest)(nil),         // 0: venomous_dashboard.auth.AuthSignupRequest
	(*AuthSignupResponse)(nil),        // 1: venomous_dashboard.auth.AuthSignupResponse
	(*AuthSignupData)(nil),            // 2: venomous_dashboard.auth.AuthSignupData
	(*AuthSigninRequest)(nil),         // 3: venomous_dashboard.auth.AuthSigninRequest
	(*AuthSigninResponse)(nil),        // 4: venomous_dashboard.auth.AuthSigninResponse
	(*AuthSigninData)(nil),            // 5: venomous_dashboard.auth.AuthSigninData
	(*AuthLogoutRequest)(nil),         // 6: venomous_dashboard.auth.AuthLogoutRequest
	(*AuthLogoutResponse)(nil),        // 7: venomous_dashboard.auth.AuthLogoutResponse
	(*AuthTokenVerifyRequest)(nil),    // 8: venomous_dashboard.auth.AuthTokenVerifyRequest
	(*AuthTokenVerifyResponse)(nil),   // 9: venomous_dashboard.auth.AuthTokenVerifyResponse
	(*AuthTokenInfoRequest)(nil),      // 10: venomous_dashboard.auth.AuthTokenInfoRequest
	(*AuthTokenInfoResponse)(nil),     // 11: venomous_dashboard.auth.AuthTokenInfoResponse
	(*AuthTokenRefreshRequest)(nil),   // 12: venomous_dashboard.auth.AuthTokenRefreshRequest
	(*AuthTokenRefreshResponse)(nil),  // 13: venomous_dashboard.auth.AuthTokenRefreshResponse
	(*AuthTokenRefreshData)(nil),      // 14: venomous_dashboard.auth.AuthTokenRefreshData
	(*UserGetProfileRequest)(nil),     // 15: venomous_dashboard.auth.UserGetProfileRequest
	(*UserGetProfileResponse)(nil),    // 16: venomous_dashboard.auth.UserGetProfileResponse
	(*UserUpdateProfileRequest)(nil),  // 17: venomous_dashboard.auth.UserUpdateProfileRequest
	(*UserUpdateProfileResponse)(nil), // 18: venomous_dashboard.auth.UserUpdateProfileResponse
	(*__common.ApiError)(nil),         // 19: venomous_dashboard.common.ApiError
	(*User)(nil),                      // 20: venomous_dashboard.auth.User
	(*AuthTokenInfo)(nil),             // 21: venomous_dashboard.auth.AuthTokenInfo
	(*UserProfile)(nil),               // 22: venomous_dashboard.auth.UserProfile
}
var file_auth_api_proto_depIdxs = []int32{
	2,  // 0: venomous_dashboard.auth.AuthSignupResponse.data:type_name -> venomous_dashboard.auth.AuthSignupData
	19, // 1: venomous_dashboard.auth.AuthSignupResponse.error:type_name -> venomous_dashboard.common.ApiError
	20, // 2: venomous_dashboard.auth.AuthSignupData.user:type_name -> venomous_dashboard.auth.User
	5,  // 3: venomous_dashboard.auth.AuthSigninResponse.data:type_name -> venomous_dashboard.auth.AuthSigninData
	19, // 4: venomous_dashboard.auth.AuthSigninResponse.error:type_name -> venomous_dashboard.common.ApiError
	20, // 5: venomous_dashboard.auth.AuthSigninData.user:type_name -> venomous_dashboard.auth.User
	19, // 6: venomous_dashboard.auth.AuthLogoutResponse.error:type_name -> venomous_dashboard.common.ApiError
	21, // 7: venomous_dashboard.auth.AuthTokenVerifyResponse.data:type_name -> venomous_dashboard.auth.AuthTokenInfo
	19, // 8: venomous_dashboard.auth.AuthTokenVerifyResponse.error:type_name -> venomous_dashboard.common.ApiError
	21, // 9: venomous_dashboard.auth.AuthTokenInfoResponse.data:type_name -> venomous_dashboard.auth.AuthTokenInfo
	19, // 10: venomous_dashboard.auth.AuthTokenInfoResponse.error:type_name -> venomous_dashboard.common.ApiError
	14, // 11: venomous_dashboard.auth.AuthTokenRefreshResponse.data:type_name -> venomous_dashboard.auth.AuthTokenRefreshData
	19, // 12: venomous_dashboard.auth.AuthTokenRefreshResponse.error:type_name -> venomous_dashboard.common.ApiError
	22, // 13: venomous_dashboard.auth.UserGetProfileResponse.data:type_name -> venomous_dashboard.auth.UserProfile
	19, // 14: venomous_dashboard.auth.UserGetProfileResponse.error:type_name -> venomous_dashboard.common.ApiError
	20, // 15: venomous_dashboard.auth.UserUpdateProfileResponse.data:type_name -> venomous_dashboard.auth.User
	19, // 16: venomous_dashboard.auth.UserUpdateProfileResponse.error:type_name -> venomous_dashboard.common.ApiError
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_auth_api_proto_init() }
func file_auth_api_proto_init() {
	if File_auth_api_proto != nil {
		return
	}
	file_auth_interface_proto_init()
	file_auth_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[11].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[13].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[16].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[17].OneofWrappers = []any{}
	file_auth_api_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_proto_rawDesc), len(file_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_api_proto_goTypes,
		DependencyIndexes: file_auth_api_proto_depIdxs,
		MessageInfos:      file_auth_api_proto_msgTypes,
	}.Build()
	File_auth_api_proto = out.File
	file_auth_api_proto_goTypes = nil
	file_auth_api_proto_depIdxs = nil
}
