// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: auth/interface.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_auth_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Role) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Role) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Role) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RoleId        string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AvatarPath    *string                `protobuf:"bytes,5,opt,name=avatar_path,json=avatarPath,proto3,oneof" json:"avatar_path,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *User) GetAvatarPath() string {
	if x != nil && x.AvatarPath != nil {
		return *x.AvatarPath
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type AuthUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash      string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	LastLogin         *string                `protobuf:"bytes,6,opt,name=last_login,json=lastLogin,proto3,oneof" json:"last_login,omitempty"`
	LoginFailureCount int32                  `protobuf:"varint,7,opt,name=login_failure_count,json=loginFailureCount,proto3" json:"login_failure_count,omitempty"`
	IsLoginLocked     bool                   `protobuf:"varint,8,opt,name=is_login_locked,json=isLoginLocked,proto3" json:"is_login_locked,omitempty"`
	DeletedAt         *string                `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthUser) Reset() {
	*x = AuthUser{}
	mi := &file_auth_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUser) ProtoMessage() {}

func (x *AuthUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUser.ProtoReflect.Descriptor instead.
func (*AuthUser) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthUser) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *AuthUser) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *AuthUser) GetLastLogin() string {
	if x != nil && x.LastLogin != nil {
		return *x.LastLogin
	}
	return ""
}

func (x *AuthUser) GetLoginFailureCount() int32 {
	if x != nil {
		return x.LoginFailureCount
	}
	return 0
}

func (x *AuthUser) GetIsLoginLocked() bool {
	if x != nil {
		return x.IsLoginLocked
	}
	return false
}

func (x *AuthUser) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields from User table
	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email      string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name       string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RoleId     string  `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AvatarPath *string `protobuf:"bytes,5,opt,name=avatar_path,json=avatarPath,proto3,oneof" json:"avatar_path,omitempty"`
	CreatedAt  string  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt  *string `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// Fields from AuthUser table
	EmailVerified     bool    `protobuf:"varint,9,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	LastLogin         *string `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3,oneof" json:"last_login,omitempty"`
	LoginFailureCount int32   `protobuf:"varint,11,opt,name=login_failure_count,json=loginFailureCount,proto3" json:"login_failure_count,omitempty"`
	IsLoginLocked     bool    `protobuf:"varint,12,opt,name=is_login_locked,json=isLoginLocked,proto3" json:"is_login_locked,omitempty"`
	// Fields from Role table
	RoleName      string `protobuf:"bytes,13,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_auth_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UserProfile) GetAvatarPath() string {
	if x != nil && x.AvatarPath != nil {
		return *x.AvatarPath
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserProfile) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *UserProfile) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UserProfile) GetLastLogin() string {
	if x != nil && x.LastLogin != nil {
		return *x.LastLogin
	}
	return ""
}

func (x *UserProfile) GetLoginFailureCount() int32 {
	if x != nil {
		return x.LoginFailureCount
	}
	return 0
}

func (x *UserProfile) GetIsLoginLocked() bool {
	if x != nil {
		return x.IsLoginLocked
	}
	return false
}

func (x *UserProfile) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuedAt      string                 `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_auth_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{4}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthToken) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AuthToken) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

type AuthTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenInfo) Reset() {
	*x = AuthTokenInfo{}
	mi := &file_auth_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenInfo) ProtoMessage() {}

func (x *AuthTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenInfo.ProtoReflect.Descriptor instead.
func (*AuthTokenInfo) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{5}
}

func (x *AuthTokenInfo) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthTokenInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthTokenInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthTokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthTokenInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthTokenInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthTokenInfo) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

var File_auth_interface_proto protoreflect.FileDescriptor

const file_auth_interface_proto_rawDesc = "" +
	"\n" +
	"\x14auth/interface.proto\x12\x17venomous_dashboard.auth\"\xd2\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\tH\x01R\tdeletedAt\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_deleted_at\"\x80\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12$\n" +
	"\vavatar_path\x18\x05 \x01(\tH\x00R\n" +
	"avatarPath\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tH\x01R\tdeletedAt\x88\x01\x01B\x0e\n" +
	"\f_avatar_pathB\r\n" +
	"\v_deleted_at\"\xd3\x02\n" +
	"\bAuthUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x12\"\n" +
	"\n" +
	"last_login\x18\x06 \x01(\tH\x00R\tlastLogin\x88\x01\x01\x12.\n" +
	"\x13login_failure_count\x18\a \x01(\x05R\x11loginFailureCount\x12&\n" +
	"\x0fis_login_locked\x18\b \x01(\bR\risLoginLocked\x12\"\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tH\x01R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_last_loginB\r\n" +
	"\v_deleted_at\"\xd6\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12$\n" +
	"\vavatar_path\x18\x05 \x01(\tH\x00R\n" +
	"avatarPath\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tH\x01R\tdeletedAt\x88\x01\x01\x12%\n" +
	"\x0eemail_verified\x18\t \x01(\bR\remailVerified\x12\"\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\tH\x02R\tlastLogin\x88\x01\x01\x12.\n" +
	"\x13login_failure_count\x18\v \x01(\x05R\x11loginFailureCount\x12&\n" +
	"\x0fis_login_locked\x18\f \x01(\bR\risLoginLocked\x12\x1b\n" +
	"\trole_name\x18\r \x01(\tR\broleNameB\x0e\n" +
	"\f_avatar_pathB\r\n" +
	"\v_deleted_atB\r\n" +
	"\v_last_login\"]\n" +
	"\tAuthToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1b\n" +
	"\tissued_at\x18\x03 \x01(\tR\bissuedAt\"\xb8\x01\n" +
	"\rAuthTokenInfo\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\tissued_at\x18\a \x01(\x03R\bissuedAtBOZMgithub.com/venomous-dashboard/api-gateway/internal/types/proto_generated/authb\x06proto3"

var (
	file_auth_interface_proto_rawDescOnce sync.Once
	file_auth_interface_proto_rawDescData []byte
)

func file_auth_interface_proto_rawDescGZIP() []byte {
	file_auth_interface_proto_rawDescOnce.Do(func() {
		file_auth_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_interface_proto_rawDesc), len(file_auth_interface_proto_rawDesc)))
	})
	return file_auth_interface_proto_rawDescData
}

var file_auth_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_interface_proto_goTypes = []any{
	(*Role)(nil),          // 0: venomous_dashboard.auth.Role
	(*User)(nil),          // 1: venomous_dashboard.auth.User
	(*AuthUser)(nil),      // 2: venomous_dashboard.auth.AuthUser
	(*UserProfile)(nil),   // 3: venomous_dashboard.auth.UserProfile
	(*AuthToken)(nil),     // 4: venomous_dashboard.auth.AuthToken
	(*AuthTokenInfo)(nil), // 5: venomous_dashboard.auth.AuthTokenInfo
}
var file_auth_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_interface_proto_init() }
func file_auth_interface_proto_init() {
	if File_auth_interface_proto != nil {
		return
	}
	file_auth_interface_proto_msgTypes[0].OneofWrappers = []any{}
	file_auth_interface_proto_msgTypes[1].OneofWrappers = []any{}
	file_auth_interface_proto_msgTypes[2].OneofWrappers = []any{}
	file_auth_interface_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_interface_proto_rawDesc), len(file_auth_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_interface_proto_goTypes,
		DependencyIndexes: file_auth_interface_proto_depIdxs,
		MessageInfos:      file_auth_interface_proto_msgTypes,
	}.Build()
	File_auth_interface_proto = out.File
	file_auth_interface_proto_goTypes = nil
	file_auth_interface_proto_depIdxs = nil
}
